name: CustomBosses
version: '1.0'
main: me.redplayer_1.custombosses.CustomBosses
description: A custom bosses plugin
authors:
  - RedPlayer_1
api-version: '1.20'
commands:
  boss:
    description: root command for all boss utilities
    usage: /boss <spawn|kill> <type>
permissions:
  custombosses.command.boss:
    description: Permission to use the base /boss command
    default: op
    children:
      custombosses.command.boss.spawn:
        description: Permission to spawn bosses (with /boss)
        default: op
      custombosses.command.boss.kill:
        description: Permission to kill bosses (with /boss)
        default: op
dependencies:
  server:
    DecentHolograms:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceHolderAPI:
      load: BEFORE
      required: false
      join-classpath: true